services:
  mysql-spva:
    image: mysql:8.0
    container_name: mysql-spva
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: victor
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: spva
    ports:
      - "3306:3306"
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql_spva_volume:/var/lib/mysql
volumes:
  mysql_spva_volume: