services:

  minio-spva:
    restart: always
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=victor
      - MINIO_ROOT_PASSWORD=senha1234567
      - MINIO_STORAGE_USE_HTTPS=false
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  mysql-spva:
    image: mysql:8.0
    container_name: mysql-spva
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: victor
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: spva
    ports:
      - "3306:3306"
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql_spva_volume:/var/lib/mysql
volumes:
  mysql_spva_volume:
