GET localhost:8000/jobs

###

GET localhost:8000/jobs/1

###

POST localhost:8000/jobs
Content-Type: application/json

{
    "user_id": "2",
    "title": "Front End Developer",
    "description": "Front End Developer with experience of 10 years in React, Next, Node.",
    "position": "Developer",
    "category": "remote"
}

###

DELETE localhost:8000/jobs/2

###

PUT localhost:8000/jobs/3
Content-Type: application/json

{
    "user_id": "2",
    "title": "Front End Developer",
    "description": "Front End Developer with experience of 10 years in React, Next, Node.",
    "position": "Developer",
    "category": "on-site"
}

###
